version: 2
updates:
  - package-ecosystem: "docker"
    directory: "python-minimal"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "R-minimal"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "julia-minimal"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "bioc-minimal"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "minimal"
    schedule:
      interval: "weekly"
