# renku: v1.dev20180723

variables:
  GIT_STRATEGY: fetch
  GIT_SSL_NO_VERIFY: "true"
  GIT_LFS_SKIP_SMUDGE: 1
  RENKU_VERSION: 0.10.4
  RENKU_BASE_IMAGE: renku/renkulab-py:3.7-d2d0b9e

stages:
  - build

image_build:
  stage: build
  image: docker:stable
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN http://$CI_REGISTRY
  script: |
    CI_COMMIT_SHA_7=$(echo $CI_COMMIT_SHA | cut -c1-7)
    docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA_7 \
      --build-arg RENKU_VERSION=${RENKU_VERSION} \
      --build-arg RENKU_BASE_IMAGE=${RENKU_BASE_IMAGE} .
    docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA_7
